services:
  finanzas-user-database:
    container_name: finanzas-user-database
    image: postgres:latest
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    volumes:
      - finanzas-user-database:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - external-network
      - internal-network
  
  finanzas-user-service:
    image: finanzas-user-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - finanzas-user-database
    environment:
      USER_PG_HOST: ${USER_DB_HOST}
      USER_PG_DATABASE: ${USER_DB_NAME}
      USER_PG_USER: ${USER_DB_USER}
      USER_PG_PASSWORD: ${USER_DB_PASSWORD}
    #    ports:
    #      - "8081:8080"
    networks:
      - internal-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.finanzas-user-service.loadbalancer.server.port=8080"
      - "traefik.http.routers.finanzas-user-service.rule=Host(`api.localhost`) && PathPrefix(`/user`)"
      - "traefik.http.routers.finanzas-user-service.middlewares=replace-microservice-path"
      - "traefik.http.middlewares.replace-microservice-path.replacepathregex.regex=^/user/?(.*)" # Obtener sub-ruta sin /user
      - "traefik.http.middlewares.replace-microservice-path.replacepathregex.replacement=/$$1" # Reemplazar la request interna con la sub-ruta

volumes:
  finanzas-user-database:

networks:
  external-network:
    external: true
  internal-network:
    external: true